#!/bin/bash

if [[ -z "$VIRTUAL_ENV" ]]; then
    # Only activate the virtualenv if we aren't in one already
    source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
    workon pocketstats
fi

# cd to the project dir so the script can find everything it needs
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
cd "${SCRIPTDIR}"

if [ ! -f pocketstats.db ]; then
    python pocketstats.py createdb
fi

python pocketstats.py updatestats
